/**
 * Shared metadata and formatting utilities for the Telemetry system.
 * This keeps the UI components focused on rendering while centralizing 
 * the documentation and math.
 */

export const TELEMETRY_METADATA = {
  cost: "Total financial footprint of all LLM coaching calls in this session.",
  savings: "Estimated money saved by serving analysis from local/global caches.",
  avgCost: "The average economic cost of each new insight generated by the Oracle.",
  tokens: "Combined input/output tokens processed by the AI model.",
  density: "Avg tokens per response; higher indicates more detailed coaching prose.",
  hitRate: "Percentage of requests served by infrastructure caches (Reuse Rate).",
  nps: "Raw search speed of the WASM engine (Nodes Per Second). Higher is stronger.",
  ttfr: "Time to First Recommendation; how fast the engine responds to a new position.",
  depthStability: "Engine search consistency; fluctuations may indicate CPU throttling.",
  depth: "The average number of moves ahead the engine is thinking.",
  ram: "Local browser memory currently allocated to the Stockfish WASM instance.",
  threads: "Number of hardware threads utilized for parallel search processing.",
  suspicion: "Highest behavioral anomaly score detected this session (100% = Busted).",
  velocity: "The rate at which suspicion points are accumulating per player move.",
  correlation: "Match rate between player moves and the engine's primary recommendations.",
  blurs: "Count of window focus losses, used as a behavioral signal for external help.",
  vault: "Total storage space consumed by your game library in the browser IDB.",
  boot: "Time taken to hydrate your entire game vault from local storage on startup.",
  ratio: "Interaction balance between study/analysis and active gameplay."
};

/**
/**
 * Formats Nodes Per Second into human-readable K/M values.
 * 
 * @param nps - The raw nodes per second number from the chess engine
 * @returns string - Formatted value, e.g., "1.2M", "450K", or "0"
 */
export const formatNps = (nps: number): string => {
  if (nps > 1000000) return (nps / 1000000).toFixed(1) + 'M';
  if (nps > 1000) return (nps / 1000).toFixed(0) + 'K';
  return nps ? nps.toString() : '0';
};

/**
 * Formats raw seconds into a human-readable duration string.
 * If the duration is less than 60 seconds, returns the seconds directly.
 * Otherwise, formats as minutes and seconds.
 * 
 * @param seconds - The raw duration in seconds
 * @returns string - Formatted duration, e.g., "45s" or "3m 15s"
 */
export const formatDuration = (seconds: number): string => {
  if (seconds < 60) return `${seconds}s`;
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}m ${s}s`;
};

/**
 * Formats raw seconds into digital clock format (mm:ss).
 * Used primarily for timers and stopwatches in active sessions.
 * 
 * @param seconds - The raw duration in seconds
 * @returns string - Digital clock format, e.g., "1:15" or "0:45"
 */
export const formatMmSs = (seconds: number): string => {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, '0')}`;
};

/**
 * Localized time formatting for telemetry logs.
 * Converts an ISO timestamp string into a localized time display.
 * 
 * @param ts - The ISO timestamp string
 * @returns string - Formatted local time, e.g., "09:30 AM" or "--:--" if empty
 */
export const formatTime = (ts: string): string => {
  if (!ts) return '--:--';
  const d = new Date(ts);
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};

